name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  crate:
    name: crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup toolchain install 1.72 \
            --profile minimal \
            --target wasm32-unknown-unknown \
            --no-self-update

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Deps
        run: make install-prod

      - name: Publish hpl-interface
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }} --package hpl-interface

  artifact:
    permissions:
      contents: write
      pull-requests: write

    name: artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup toolchain install 1.72 \
            --profile minimal \
            --target wasm32-unknown-unknown \
            --no-self-update

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Deps
        run: make install-prod

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build wasm
        run: |
          cargo generate-lockfile
          make ci-build
          mv wasm_codes.zip ${{ env.ARTIFACT_NAME }}
          sha256sum ${{ env.ARTIFACT_NAME }} > ${{ env.ARTIFACT_NAME }}.CHECKSUM
          md5sum ${{ env.ARTIFACT_NAME }} > ${{ env.ARTIFACT_NAME }}.CHECKSUM.MD5
        env:
          ARTIFACT_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip

      - name: Release Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ARTIFACT_NAME }}
            ${{ env.ARTIFACT_NAME }}.CHECKSUM
            ${{ env.ARTIFACT_NAME }}.CHECKSUM.MD5
        env:
          ARTIFACT_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
