name: test

on:
  pull_request:
    paths:
      - 'contracts/**'
      - 'packages/**'
      - 'Cargo.toml'
  push:
    branches:
      - 'main'

jobs:
  unit-test:
    strategy:
      fail-fast: true

    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Rust
        run: |
          rustup toolchain install 1.72 \
            --profile minimal \
            --target wasm32-unknown-unknown \
            --no-self-update

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --workspace --exclude hpl-tests

  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Rust
        run: |
          rustup toolchain install 1.72 \
            --profile minimal \
            --target wasm32-unknown-unknown \
            --no-self-update

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --workspace --exclude hpl-tests --codecov --output-path codecov.json

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
